version: '3'

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scrapy:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend
    command: scrapy crawlall

networks:
  backend:

volumes:
  postgres_data:
